version: '3'

services:
  mongodb:
    image: mongo:3.2
    command: mongod
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  redis:
    image: redis
    volumes:
      - redis-data:/data
    ports:
    - "6379:6379"

  elasticsearch:
    image: udata/elasticsearch
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  nginx:
    image: jwilder/nginx-proxy
    ports:
      - "7000:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  front:
    image: udata/udata
    command: front
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST:-localhost}
      - VIRTUAL_PORT=${VIRTUAL_PORT:-7000}
    links:
      - mongodb:mongodb
      - redis:redis
      - elasticsearch:elasticsearch
    volumes:
      - udata-fs:/udata/fs

  beat:
    image: udata/udata
    command: beat
    links:
      - mongodb:mongodb
      - redis:redis
      - elasticsearch:elasticsearch
    volumes:
      - udata-fs:/udata/fs

  worker:
    image: udata/udata
    command: worker
    links:
      - mongodb:mongodb
      - redis:redis
      - elasticsearch:elasticsearch
    volumes:
      - udata-fs:/udata/fs

  udata:
    image: udata/udata
    command: collect -ni /data/public
    links:
      - mongodb:mongodb
      - redis:redis
      - elasticsearch:elasticsearch
    volumes:
      - udata-fs:/udata/fs

volumes:
  udata-fs:
  mongo-data:
  redis-data:
  elasticsearch-data:
